// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/dapr/go-sdk/client"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDaprClient creates a new instance of MockDaprClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDaprClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDaprClient {
	mock := &MockDaprClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDaprClient is an autogenerated mock type for the DaprClient type
type MockDaprClient struct {
	mock.Mock
}

type MockDaprClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDaprClient) EXPECT() *MockDaprClient_Expecter {
	return &MockDaprClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockDaprClient
func (_mock *MockDaprClient) Close() {
	_mock.Called()
	return
}

// MockDaprClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockDaprClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockDaprClient_Expecter) Close() *MockDaprClient_Close_Call {
	return &MockDaprClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockDaprClient_Close_Call) Run(run func()) *MockDaprClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDaprClient_Close_Call) Return() *MockDaprClient_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDaprClient_Close_Call) RunAndReturn(run func()) *MockDaprClient_Close_Call {
	_c.Run(run)
	return _c
}

// InvokeMethod provides a mock function for the type MockDaprClient
func (_mock *MockDaprClient) InvokeMethod(ctx context.Context, appID string, methodName string, verb string) ([]byte, error) {
	ret := _mock.Called(ctx, appID, methodName, verb)

	if len(ret) == 0 {
		panic("no return value specified for InvokeMethod")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) ([]byte, error)); ok {
		return returnFunc(ctx, appID, methodName, verb)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) []byte); ok {
		r0 = returnFunc(ctx, appID, methodName, verb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, appID, methodName, verb)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDaprClient_InvokeMethod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvokeMethod'
type MockDaprClient_InvokeMethod_Call struct {
	*mock.Call
}

// InvokeMethod is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - methodName string
//   - verb string
func (_e *MockDaprClient_Expecter) InvokeMethod(ctx interface{}, appID interface{}, methodName interface{}, verb interface{}) *MockDaprClient_InvokeMethod_Call {
	return &MockDaprClient_InvokeMethod_Call{Call: _e.mock.On("InvokeMethod", ctx, appID, methodName, verb)}
}

func (_c *MockDaprClient_InvokeMethod_Call) Run(run func(ctx context.Context, appID string, methodName string, verb string)) *MockDaprClient_InvokeMethod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDaprClient_InvokeMethod_Call) Return(bytes []byte, err error) *MockDaprClient_InvokeMethod_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockDaprClient_InvokeMethod_Call) RunAndReturn(run func(ctx context.Context, appID string, methodName string, verb string) ([]byte, error)) *MockDaprClient_InvokeMethod_Call {
	_c.Call.Return(run)
	return _c
}

// PublishEvent provides a mock function for the type MockDaprClient
func (_mock *MockDaprClient) PublishEvent(ctx context.Context, pubsubName string, topicName string, data interface{}, opts ...client.PublishEventOption) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, pubsubName, topicName, data, opts)
	} else {
		tmpRet = _mock.Called(ctx, pubsubName, topicName, data)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PublishEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, interface{}, ...client.PublishEventOption) error); ok {
		r0 = returnFunc(ctx, pubsubName, topicName, data, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDaprClient_PublishEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishEvent'
type MockDaprClient_PublishEvent_Call struct {
	*mock.Call
}

// PublishEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - pubsubName string
//   - topicName string
//   - data interface{}
//   - opts ...client.PublishEventOption
func (_e *MockDaprClient_Expecter) PublishEvent(ctx interface{}, pubsubName interface{}, topicName interface{}, data interface{}, opts ...interface{}) *MockDaprClient_PublishEvent_Call {
	return &MockDaprClient_PublishEvent_Call{Call: _e.mock.On("PublishEvent",
		append([]interface{}{ctx, pubsubName, topicName, data}, opts...)...)}
}

func (_c *MockDaprClient_PublishEvent_Call) Run(run func(ctx context.Context, pubsubName string, topicName string, data interface{}, opts ...client.PublishEventOption)) *MockDaprClient_PublishEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 interface{}
		if args[3] != nil {
			arg3 = args[3].(interface{})
		}
		var arg4 []client.PublishEventOption
		var variadicArgs []client.PublishEventOption
		if len(args) > 4 {
			variadicArgs = args[4].([]client.PublishEventOption)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *MockDaprClient_PublishEvent_Call) Return(err error) *MockDaprClient_PublishEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDaprClient_PublishEvent_Call) RunAndReturn(run func(ctx context.Context, pubsubName string, topicName string, data interface{}, opts ...client.PublishEventOption) error) *MockDaprClient_PublishEvent_Call {
	_c.Call.Return(run)
	return _c
}
