// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics_query.sql

package sqlc

import (
	"context"
)

const countClicksByShortCode = `-- name: CountClicksByShortCode :one
SELECT COUNT(*) as total_clicks FROM clicks WHERE short_code = ?
`

func (q *Queries) CountClicksByShortCode(ctx context.Context, shortCode string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countClicksByShortCode, shortCode)
	var total_clicks int64
	err := row.Scan(&total_clicks)
	return total_clicks, err
}

const insertClick = `-- name: InsertClick :exec
INSERT INTO clicks (short_code, clicked_at)
VALUES (?, ?)
`

type InsertClickParams struct {
	ShortCode string `json:"short_code"`
	ClickedAt int64  `json:"clicked_at"`
}

func (q *Queries) InsertClick(ctx context.Context, arg InsertClickParams) error {
	_, err := q.db.ExecContext(ctx, insertClick, arg.ShortCode, arg.ClickedAt)
	return err
}
