// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

type Click struct {
	ID        int64  `json:"id"`
	ShortCode string `json:"short_code"`
	ClickedAt int64  `json:"clicked_at"`
}
