// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CountByCountryInRange(ctx context.Context, arg CountByCountryInRangeParams) ([]CountByCountryInRangeRow, error)
	CountByDeviceInRange(ctx context.Context, arg CountByDeviceInRangeParams) ([]CountByDeviceInRangeRow, error)
	CountBySourceInRange(ctx context.Context, arg CountBySourceInRangeParams) ([]CountBySourceInRangeRow, error)
	CountClicksByShortCode(ctx context.Context, shortCode string) (int64, error)
	CountClicksInRange(ctx context.Context, arg CountClicksInRangeParams) (int64, error)
	DeleteClicksByShortCode(ctx context.Context, shortCode string) error
	GetClickDetails(ctx context.Context, arg GetClickDetailsParams) ([]Click, error)
	InsertEnrichedClick(ctx context.Context, arg InsertEnrichedClickParams) error
}

var _ Querier = (*Queries)(nil)
