// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CountClicksByShortCode(ctx context.Context, shortCode string) (int64, error)
	InsertClick(ctx context.Context, arg InsertClickParams) error
}

var _ Querier = (*Queries)(nil)
