// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	clicksFieldNames          = builder.RawFieldNames(&Clicks{}, true)
	clicksRows                = strings.Join(clicksFieldNames, ",")
	clicksRowsExpectAutoSet   = strings.Join(stringx.Remove(clicksFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	clicksRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(clicksFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	clicksModel interface {
		Insert(ctx context.Context, data *Clicks) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*Clicks, error)
		Update(ctx context.Context, data *Clicks) error
		Delete(ctx context.Context, id string) error
	}

	defaultClicksModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Clicks struct {
		Id            string    `db:"id"`
		ShortCode     string    `db:"short_code"`
		ClickedAt     time.Time `db:"clicked_at"`
		CountryCode   string    `db:"country_code"`
		DeviceType    string    `db:"device_type"`
		TrafficSource string    `db:"traffic_source"`
	}
)

func newClicksModel(conn sqlx.SqlConn) *defaultClicksModel {
	return &defaultClicksModel{
		conn:  conn,
		table: `"public"."clicks"`,
	}
}

func (m *defaultClicksModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultClicksModel) FindOne(ctx context.Context, id string) (*Clicks, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", clicksRows, m.table)
	var resp Clicks
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultClicksModel) Insert(ctx context.Context, data *Clicks) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6)", m.table, clicksRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.ShortCode, data.ClickedAt, data.CountryCode, data.DeviceType, data.TrafficSource)
	return ret, err
}

func (m *defaultClicksModel) Update(ctx context.Context, data *Clicks) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, clicksRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.ShortCode, data.ClickedAt, data.CountryCode, data.DeviceType, data.TrafficSource)
	return err
}

func (m *defaultClicksModel) tableName() string {
	return m.table
}
