version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - goconst
    - unparam

  settings:
    goconst:
      min-len: 3
      min-occurrences: 5
    staticcheck:
      checks:
        - "all"
        - "-SA5008"  # go-zero uses custom json tags (optional, default)
        - "-ST1000"  # go-zero services lack package comments by convention
        - "-ST1003"  # go-zero uses BaseUrl/AnalyticsRpc naming convention
        - "-ST1020"  # goctl generates non-standard comment format

  exclusions:
    generated: strict
    presets:
      - std-error-handling
      - common-false-positives
    rules:
      - path: _test\.go
        linters:
          - errcheck
      - text: "Error return value of `w\\.Write` is not checked"
        linters:
          - errcheck
    paths:
      - services/analytics-rpc/analytics  # Generated protobuf code
      - ".*_gen\\.go$"  # goctl-generated model files

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: strict
    paths:
      - services/analytics-rpc/analytics
      - ".*_gen\\.go$"
