dir: "{{.InterfaceDir}}/../testutil/mocks"
pkgname: mocks
structname: "Mock{{.InterfaceName}}"
filename: "{{.InterfaceName}}.go"
packages:
  go-shortener/internal/urlservice/usecase:
    interfaces:
      URLRepository:
      DaprClient:
  go-shortener/internal/analytics/usecase:
    interfaces:
      ClickRepository:
      GeoIPResolver:
      DeviceDetector:
      RefererClassifier:
