# Build stage
FROM golang:1.24 AS builder
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /app/analytics-service ./cmd/analytics-service

# Runtime stage
FROM gcr.io/distroless/static-debian12:latest
COPY --from=builder /app/analytics-service /analytics-service
EXPOSE 8081
ENTRYPOINT ["/analytics-service"]
