# Build stage
FROM golang:1.24 AS builder
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /app/url-service ./cmd/url-service

# Runtime stage
FROM gcr.io/distroless/static-debian12:latest
COPY --from=builder /app/url-service /url-service
EXPOSE 8080
ENTRYPOINT ["/url-service"]
