// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	urlsFieldNames          = builder.RawFieldNames(&Urls{}, true)
	urlsRows                = strings.Join(urlsFieldNames, ",")
	urlsRowsExpectAutoSet   = strings.Join(stringx.Remove(urlsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	urlsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(urlsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	urlsModel interface {
		Insert(ctx context.Context, data *Urls) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*Urls, error)
		FindOneByShortCode(ctx context.Context, shortCode string) (*Urls, error)
		Update(ctx context.Context, data *Urls) error
		Delete(ctx context.Context, id string) error
	}

	defaultUrlsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Urls struct {
		Id          string    `db:"id"`
		ShortCode   string    `db:"short_code"`
		OriginalUrl string    `db:"original_url"`
		ClickCount  int64     `db:"click_count"`
		CreatedAt   time.Time `db:"created_at"`
	}
)

func newUrlsModel(conn sqlx.SqlConn) *defaultUrlsModel {
	return &defaultUrlsModel{
		conn:  conn,
		table: `"public"."urls"`,
	}
}

func (m *defaultUrlsModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUrlsModel) FindOne(ctx context.Context, id string) (*Urls, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", urlsRows, m.table)
	var resp Urls
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUrlsModel) FindOneByShortCode(ctx context.Context, shortCode string) (*Urls, error) {
	var resp Urls
	query := fmt.Sprintf("select %s from %s where short_code = $1 limit 1", urlsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, shortCode)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUrlsModel) Insert(ctx context.Context, data *Urls) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4)", m.table, urlsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.ShortCode, data.OriginalUrl, data.ClickCount)
	return ret, err
}

func (m *defaultUrlsModel) Update(ctx context.Context, newData *Urls) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, urlsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.ShortCode, newData.OriginalUrl, newData.ClickCount)
	return err
}

func (m *defaultUrlsModel) tableName() string {
	return m.table
}
