// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
)

const createURL = `-- name: CreateURL :one
INSERT INTO urls (short_code, original_url)
VALUES (?, ?)
RETURNING id, short_code, original_url, created_at
`

type CreateURLParams struct {
	ShortCode   string `json:"short_code"`
	OriginalUrl string `json:"original_url"`
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, createURL, arg.ShortCode, arg.OriginalUrl)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.CreatedAt,
	)
	return i, err
}

const findByOriginalURL = `-- name: FindByOriginalURL :one
SELECT id, short_code, original_url, created_at FROM urls WHERE original_url = ? LIMIT 1
`

func (q *Queries) FindByOriginalURL(ctx context.Context, originalUrl string) (Url, error) {
	row := q.db.QueryRowContext(ctx, findByOriginalURL, originalUrl)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.CreatedAt,
	)
	return i, err
}

const findByShortCode = `-- name: FindByShortCode :one
SELECT id, short_code, original_url, created_at FROM urls WHERE short_code = ? LIMIT 1
`

func (q *Queries) FindByShortCode(ctx context.Context, shortCode string) (Url, error) {
	row := q.db.QueryRowContext(ctx, findByShortCode, shortCode)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.CreatedAt,
	)
	return i, err
}
