// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateURL(ctx context.Context, arg CreateURLParams) (Url, error)
	FindByOriginalURL(ctx context.Context, originalUrl string) (Url, error)
	FindByShortCode(ctx context.Context, shortCode string) (Url, error)
}

var _ Querier = (*Queries)(nil)
