// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: analytics.proto

package server

import (
	"context"

	"go-shortener/services/analytics-rpc/analytics"
	"go-shortener/services/analytics-rpc/internal/logic"
	"go-shortener/services/analytics-rpc/internal/svc"
)

type AnalyticsServer struct {
	svcCtx *svc.ServiceContext
	analytics.UnimplementedAnalyticsServer
}

func NewAnalyticsServer(svcCtx *svc.ServiceContext) *AnalyticsServer {
	return &AnalyticsServer{
		svcCtx: svcCtx,
	}
}

func (s *AnalyticsServer) GetClickCount(ctx context.Context, in *analytics.GetClickCountRequest) (*analytics.GetClickCountResponse, error) {
	l := logic.NewGetClickCountLogic(ctx, s.svcCtx)
	return l.GetClickCount(in)
}
