// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type DeleteLinkRequest struct {
	Code string `path:"code"`
}

type LinkDetailRequest struct {
	Code string `path:"code"`
}

type LinkDetailResponse struct {
	ShortCode   string `json:"short_code"`
	OriginalUrl string `json:"original_url"`
	CreatedAt   int64  `json:"created_at"`
	TotalClicks int64  `json:"total_clicks"`
}

type LinkItem struct {
	ShortCode   string `json:"short_code"`
	OriginalUrl string `json:"original_url"`
	CreatedAt   int64  `json:"created_at"`
}

type LinkListRequest struct {
	Page    int    `form:"page,default=1,range=[1:]"`
	PerPage int    `form:"per_page,default=20,range=[1:100]"`
	Sort    string `form:"sort,default=created_at,options=created_at|original_url"`
	Order   string `form:"order,default=desc,options=asc|desc"`
	Search  string `form:"search,optional"`
}

type LinkListResponse struct {
	Links      []LinkItem `json:"links"`
	Page       int        `json:"page"`
	PerPage    int        `json:"per_page"`
	TotalPages int        `json:"total_pages"`
	TotalCount int64      `json:"total_count"`
}

type RedirectRequest struct {
	Code string `path:"code"`
}

type ShortenRequest struct {
	OriginalUrl string `json:"original_url"`
}

type ShortenResponse struct {
	ShortCode   string `json:"short_code"`
	ShortUrl    string `json:"short_url"`
	OriginalUrl string `json:"original_url"`
}
