// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-shortener/internal/analytics/usecase"

	mock "github.com/stretchr/testify/mock"
)

// NewMockClickRepository creates a new instance of MockClickRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClickRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClickRepository {
	mock := &MockClickRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClickRepository is an autogenerated mock type for the ClickRepository type
type MockClickRepository struct {
	mock.Mock
}

type MockClickRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClickRepository) EXPECT() *MockClickRepository_Expecter {
	return &MockClickRepository_Expecter{mock: &_m.Mock}
}

// CountByCountryInRange provides a mock function for the type MockClickRepository
func (_mock *MockClickRepository) CountByCountryInRange(ctx context.Context, shortCode string, from int64, to int64) ([]usecase.GroupCount, error) {
	ret := _mock.Called(ctx, shortCode, from, to)

	if len(ret) == 0 {
		panic("no return value specified for CountByCountryInRange")
	}

	var r0 []usecase.GroupCount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64) ([]usecase.GroupCount, error)); ok {
		return returnFunc(ctx, shortCode, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64) []usecase.GroupCount); ok {
		r0 = returnFunc(ctx, shortCode, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]usecase.GroupCount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64, int64) error); ok {
		r1 = returnFunc(ctx, shortCode, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClickRepository_CountByCountryInRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByCountryInRange'
type MockClickRepository_CountByCountryInRange_Call struct {
	*mock.Call
}

// CountByCountryInRange is a helper method to define mock.On call
//   - ctx context.Context
//   - shortCode string
//   - from int64
//   - to int64
func (_e *MockClickRepository_Expecter) CountByCountryInRange(ctx interface{}, shortCode interface{}, from interface{}, to interface{}) *MockClickRepository_CountByCountryInRange_Call {
	return &MockClickRepository_CountByCountryInRange_Call{Call: _e.mock.On("CountByCountryInRange", ctx, shortCode, from, to)}
}

func (_c *MockClickRepository_CountByCountryInRange_Call) Run(run func(ctx context.Context, shortCode string, from int64, to int64)) *MockClickRepository_CountByCountryInRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClickRepository_CountByCountryInRange_Call) Return(groupCounts []usecase.GroupCount, err error) *MockClickRepository_CountByCountryInRange_Call {
	_c.Call.Return(groupCounts, err)
	return _c
}

func (_c *MockClickRepository_CountByCountryInRange_Call) RunAndReturn(run func(ctx context.Context, shortCode string, from int64, to int64) ([]usecase.GroupCount, error)) *MockClickRepository_CountByCountryInRange_Call {
	_c.Call.Return(run)
	return _c
}

// CountByDeviceInRange provides a mock function for the type MockClickRepository
func (_mock *MockClickRepository) CountByDeviceInRange(ctx context.Context, shortCode string, from int64, to int64) ([]usecase.GroupCount, error) {
	ret := _mock.Called(ctx, shortCode, from, to)

	if len(ret) == 0 {
		panic("no return value specified for CountByDeviceInRange")
	}

	var r0 []usecase.GroupCount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64) ([]usecase.GroupCount, error)); ok {
		return returnFunc(ctx, shortCode, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64) []usecase.GroupCount); ok {
		r0 = returnFunc(ctx, shortCode, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]usecase.GroupCount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64, int64) error); ok {
		r1 = returnFunc(ctx, shortCode, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClickRepository_CountByDeviceInRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByDeviceInRange'
type MockClickRepository_CountByDeviceInRange_Call struct {
	*mock.Call
}

// CountByDeviceInRange is a helper method to define mock.On call
//   - ctx context.Context
//   - shortCode string
//   - from int64
//   - to int64
func (_e *MockClickRepository_Expecter) CountByDeviceInRange(ctx interface{}, shortCode interface{}, from interface{}, to interface{}) *MockClickRepository_CountByDeviceInRange_Call {
	return &MockClickRepository_CountByDeviceInRange_Call{Call: _e.mock.On("CountByDeviceInRange", ctx, shortCode, from, to)}
}

func (_c *MockClickRepository_CountByDeviceInRange_Call) Run(run func(ctx context.Context, shortCode string, from int64, to int64)) *MockClickRepository_CountByDeviceInRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClickRepository_CountByDeviceInRange_Call) Return(groupCounts []usecase.GroupCount, err error) *MockClickRepository_CountByDeviceInRange_Call {
	_c.Call.Return(groupCounts, err)
	return _c
}

func (_c *MockClickRepository_CountByDeviceInRange_Call) RunAndReturn(run func(ctx context.Context, shortCode string, from int64, to int64) ([]usecase.GroupCount, error)) *MockClickRepository_CountByDeviceInRange_Call {
	_c.Call.Return(run)
	return _c
}

// CountByShortCode provides a mock function for the type MockClickRepository
func (_mock *MockClickRepository) CountByShortCode(ctx context.Context, shortCode string) (int64, error) {
	ret := _mock.Called(ctx, shortCode)

	if len(ret) == 0 {
		panic("no return value specified for CountByShortCode")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, shortCode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, shortCode)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, shortCode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClickRepository_CountByShortCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByShortCode'
type MockClickRepository_CountByShortCode_Call struct {
	*mock.Call
}

// CountByShortCode is a helper method to define mock.On call
//   - ctx context.Context
//   - shortCode string
func (_e *MockClickRepository_Expecter) CountByShortCode(ctx interface{}, shortCode interface{}) *MockClickRepository_CountByShortCode_Call {
	return &MockClickRepository_CountByShortCode_Call{Call: _e.mock.On("CountByShortCode", ctx, shortCode)}
}

func (_c *MockClickRepository_CountByShortCode_Call) Run(run func(ctx context.Context, shortCode string)) *MockClickRepository_CountByShortCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClickRepository_CountByShortCode_Call) Return(n int64, err error) *MockClickRepository_CountByShortCode_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockClickRepository_CountByShortCode_Call) RunAndReturn(run func(ctx context.Context, shortCode string) (int64, error)) *MockClickRepository_CountByShortCode_Call {
	_c.Call.Return(run)
	return _c
}

// CountBySourceInRange provides a mock function for the type MockClickRepository
func (_mock *MockClickRepository) CountBySourceInRange(ctx context.Context, shortCode string, from int64, to int64) ([]usecase.GroupCount, error) {
	ret := _mock.Called(ctx, shortCode, from, to)

	if len(ret) == 0 {
		panic("no return value specified for CountBySourceInRange")
	}

	var r0 []usecase.GroupCount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64) ([]usecase.GroupCount, error)); ok {
		return returnFunc(ctx, shortCode, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64) []usecase.GroupCount); ok {
		r0 = returnFunc(ctx, shortCode, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]usecase.GroupCount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64, int64) error); ok {
		r1 = returnFunc(ctx, shortCode, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClickRepository_CountBySourceInRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountBySourceInRange'
type MockClickRepository_CountBySourceInRange_Call struct {
	*mock.Call
}

// CountBySourceInRange is a helper method to define mock.On call
//   - ctx context.Context
//   - shortCode string
//   - from int64
//   - to int64
func (_e *MockClickRepository_Expecter) CountBySourceInRange(ctx interface{}, shortCode interface{}, from interface{}, to interface{}) *MockClickRepository_CountBySourceInRange_Call {
	return &MockClickRepository_CountBySourceInRange_Call{Call: _e.mock.On("CountBySourceInRange", ctx, shortCode, from, to)}
}

func (_c *MockClickRepository_CountBySourceInRange_Call) Run(run func(ctx context.Context, shortCode string, from int64, to int64)) *MockClickRepository_CountBySourceInRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClickRepository_CountBySourceInRange_Call) Return(groupCounts []usecase.GroupCount, err error) *MockClickRepository_CountBySourceInRange_Call {
	_c.Call.Return(groupCounts, err)
	return _c
}

func (_c *MockClickRepository_CountBySourceInRange_Call) RunAndReturn(run func(ctx context.Context, shortCode string, from int64, to int64) ([]usecase.GroupCount, error)) *MockClickRepository_CountBySourceInRange_Call {
	_c.Call.Return(run)
	return _c
}

// CountInRange provides a mock function for the type MockClickRepository
func (_mock *MockClickRepository) CountInRange(ctx context.Context, shortCode string, from int64, to int64) (int64, error) {
	ret := _mock.Called(ctx, shortCode, from, to)

	if len(ret) == 0 {
		panic("no return value specified for CountInRange")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64) (int64, error)); ok {
		return returnFunc(ctx, shortCode, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64) int64); ok {
		r0 = returnFunc(ctx, shortCode, from, to)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64, int64) error); ok {
		r1 = returnFunc(ctx, shortCode, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClickRepository_CountInRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountInRange'
type MockClickRepository_CountInRange_Call struct {
	*mock.Call
}

// CountInRange is a helper method to define mock.On call
//   - ctx context.Context
//   - shortCode string
//   - from int64
//   - to int64
func (_e *MockClickRepository_Expecter) CountInRange(ctx interface{}, shortCode interface{}, from interface{}, to interface{}) *MockClickRepository_CountInRange_Call {
	return &MockClickRepository_CountInRange_Call{Call: _e.mock.On("CountInRange", ctx, shortCode, from, to)}
}

func (_c *MockClickRepository_CountInRange_Call) Run(run func(ctx context.Context, shortCode string, from int64, to int64)) *MockClickRepository_CountInRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClickRepository_CountInRange_Call) Return(n int64, err error) *MockClickRepository_CountInRange_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockClickRepository_CountInRange_Call) RunAndReturn(run func(ctx context.Context, shortCode string, from int64, to int64) (int64, error)) *MockClickRepository_CountInRange_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByShortCode provides a mock function for the type MockClickRepository
func (_mock *MockClickRepository) DeleteByShortCode(ctx context.Context, shortCode string) error {
	ret := _mock.Called(ctx, shortCode)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByShortCode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, shortCode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClickRepository_DeleteByShortCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByShortCode'
type MockClickRepository_DeleteByShortCode_Call struct {
	*mock.Call
}

// DeleteByShortCode is a helper method to define mock.On call
//   - ctx context.Context
//   - shortCode string
func (_e *MockClickRepository_Expecter) DeleteByShortCode(ctx interface{}, shortCode interface{}) *MockClickRepository_DeleteByShortCode_Call {
	return &MockClickRepository_DeleteByShortCode_Call{Call: _e.mock.On("DeleteByShortCode", ctx, shortCode)}
}

func (_c *MockClickRepository_DeleteByShortCode_Call) Run(run func(ctx context.Context, shortCode string)) *MockClickRepository_DeleteByShortCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClickRepository_DeleteByShortCode_Call) Return(err error) *MockClickRepository_DeleteByShortCode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClickRepository_DeleteByShortCode_Call) RunAndReturn(run func(ctx context.Context, shortCode string) error) *MockClickRepository_DeleteByShortCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetClickDetails provides a mock function for the type MockClickRepository
func (_mock *MockClickRepository) GetClickDetails(ctx context.Context, shortCode string, cursorTimestamp int64, limit int) (*usecase.PaginatedClicks, error) {
	ret := _mock.Called(ctx, shortCode, cursorTimestamp, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetClickDetails")
	}

	var r0 *usecase.PaginatedClicks
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int) (*usecase.PaginatedClicks, error)); ok {
		return returnFunc(ctx, shortCode, cursorTimestamp, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int) *usecase.PaginatedClicks); ok {
		r0 = returnFunc(ctx, shortCode, cursorTimestamp, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.PaginatedClicks)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64, int) error); ok {
		r1 = returnFunc(ctx, shortCode, cursorTimestamp, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClickRepository_GetClickDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClickDetails'
type MockClickRepository_GetClickDetails_Call struct {
	*mock.Call
}

// GetClickDetails is a helper method to define mock.On call
//   - ctx context.Context
//   - shortCode string
//   - cursorTimestamp int64
//   - limit int
func (_e *MockClickRepository_Expecter) GetClickDetails(ctx interface{}, shortCode interface{}, cursorTimestamp interface{}, limit interface{}) *MockClickRepository_GetClickDetails_Call {
	return &MockClickRepository_GetClickDetails_Call{Call: _e.mock.On("GetClickDetails", ctx, shortCode, cursorTimestamp, limit)}
}

func (_c *MockClickRepository_GetClickDetails_Call) Run(run func(ctx context.Context, shortCode string, cursorTimestamp int64, limit int)) *MockClickRepository_GetClickDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClickRepository_GetClickDetails_Call) Return(paginatedClicks *usecase.PaginatedClicks, err error) *MockClickRepository_GetClickDetails_Call {
	_c.Call.Return(paginatedClicks, err)
	return _c
}

func (_c *MockClickRepository_GetClickDetails_Call) RunAndReturn(run func(ctx context.Context, shortCode string, cursorTimestamp int64, limit int) (*usecase.PaginatedClicks, error)) *MockClickRepository_GetClickDetails_Call {
	_c.Call.Return(run)
	return _c
}

// InsertClick provides a mock function for the type MockClickRepository
func (_mock *MockClickRepository) InsertClick(ctx context.Context, shortCode string, clickedAt int64, countryCode string, deviceType string, trafficSource string) error {
	ret := _mock.Called(ctx, shortCode, clickedAt, countryCode, deviceType, trafficSource)

	if len(ret) == 0 {
		panic("no return value specified for InsertClick")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, string, string, string) error); ok {
		r0 = returnFunc(ctx, shortCode, clickedAt, countryCode, deviceType, trafficSource)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClickRepository_InsertClick_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertClick'
type MockClickRepository_InsertClick_Call struct {
	*mock.Call
}

// InsertClick is a helper method to define mock.On call
//   - ctx context.Context
//   - shortCode string
//   - clickedAt int64
//   - countryCode string
//   - deviceType string
//   - trafficSource string
func (_e *MockClickRepository_Expecter) InsertClick(ctx interface{}, shortCode interface{}, clickedAt interface{}, countryCode interface{}, deviceType interface{}, trafficSource interface{}) *MockClickRepository_InsertClick_Call {
	return &MockClickRepository_InsertClick_Call{Call: _e.mock.On("InsertClick", ctx, shortCode, clickedAt, countryCode, deviceType, trafficSource)}
}

func (_c *MockClickRepository_InsertClick_Call) Run(run func(ctx context.Context, shortCode string, clickedAt int64, countryCode string, deviceType string, trafficSource string)) *MockClickRepository_InsertClick_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockClickRepository_InsertClick_Call) Return(err error) *MockClickRepository_InsertClick_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClickRepository_InsertClick_Call) RunAndReturn(run func(ctx context.Context, shortCode string, clickedAt int64, countryCode string, deviceType string, trafficSource string) error) *MockClickRepository_InsertClick_Call {
	_c.Call.Return(run)
	return _c
}
