// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockDeviceDetector creates a new instance of MockDeviceDetector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeviceDetector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeviceDetector {
	mock := &MockDeviceDetector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeviceDetector is an autogenerated mock type for the DeviceDetector type
type MockDeviceDetector struct {
	mock.Mock
}

type MockDeviceDetector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeviceDetector) EXPECT() *MockDeviceDetector_Expecter {
	return &MockDeviceDetector_Expecter{mock: &_m.Mock}
}

// DetectDevice provides a mock function for the type MockDeviceDetector
func (_mock *MockDeviceDetector) DetectDevice(uaString string) string {
	ret := _mock.Called(uaString)

	if len(ret) == 0 {
		panic("no return value specified for DetectDevice")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(uaString)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDeviceDetector_DetectDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DetectDevice'
type MockDeviceDetector_DetectDevice_Call struct {
	*mock.Call
}

// DetectDevice is a helper method to define mock.On call
//   - uaString string
func (_e *MockDeviceDetector_Expecter) DetectDevice(uaString interface{}) *MockDeviceDetector_DetectDevice_Call {
	return &MockDeviceDetector_DetectDevice_Call{Call: _e.mock.On("DetectDevice", uaString)}
}

func (_c *MockDeviceDetector_DetectDevice_Call) Run(run func(uaString string)) *MockDeviceDetector_DetectDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDeviceDetector_DetectDevice_Call) Return(s string) *MockDeviceDetector_DetectDevice_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDeviceDetector_DetectDevice_Call) RunAndReturn(run func(uaString string) string) *MockDeviceDetector_DetectDevice_Call {
	_c.Call.Return(run)
	return _c
}
