// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockGeoIPResolver creates a new instance of MockGeoIPResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGeoIPResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGeoIPResolver {
	mock := &MockGeoIPResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGeoIPResolver is an autogenerated mock type for the GeoIPResolver type
type MockGeoIPResolver struct {
	mock.Mock
}

type MockGeoIPResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGeoIPResolver) EXPECT() *MockGeoIPResolver_Expecter {
	return &MockGeoIPResolver_Expecter{mock: &_m.Mock}
}

// ResolveCountry provides a mock function for the type MockGeoIPResolver
func (_mock *MockGeoIPResolver) ResolveCountry(ipStr string) string {
	ret := _mock.Called(ipStr)

	if len(ret) == 0 {
		panic("no return value specified for ResolveCountry")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(ipStr)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockGeoIPResolver_ResolveCountry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveCountry'
type MockGeoIPResolver_ResolveCountry_Call struct {
	*mock.Call
}

// ResolveCountry is a helper method to define mock.On call
//   - ipStr string
func (_e *MockGeoIPResolver_Expecter) ResolveCountry(ipStr interface{}) *MockGeoIPResolver_ResolveCountry_Call {
	return &MockGeoIPResolver_ResolveCountry_Call{Call: _e.mock.On("ResolveCountry", ipStr)}
}

func (_c *MockGeoIPResolver_ResolveCountry_Call) Run(run func(ipStr string)) *MockGeoIPResolver_ResolveCountry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGeoIPResolver_ResolveCountry_Call) Return(s string) *MockGeoIPResolver_ResolveCountry_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockGeoIPResolver_ResolveCountry_Call) RunAndReturn(run func(ipStr string) string) *MockGeoIPResolver_ResolveCountry_Call {
	_c.Call.Return(run)
	return _c
}
