// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockRefererClassifier creates a new instance of MockRefererClassifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefererClassifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefererClassifier {
	mock := &MockRefererClassifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRefererClassifier is an autogenerated mock type for the RefererClassifier type
type MockRefererClassifier struct {
	mock.Mock
}

type MockRefererClassifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefererClassifier) EXPECT() *MockRefererClassifier_Expecter {
	return &MockRefererClassifier_Expecter{mock: &_m.Mock}
}

// ClassifySource provides a mock function for the type MockRefererClassifier
func (_mock *MockRefererClassifier) ClassifySource(refererStr string) string {
	ret := _mock.Called(refererStr)

	if len(ret) == 0 {
		panic("no return value specified for ClassifySource")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(refererStr)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockRefererClassifier_ClassifySource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClassifySource'
type MockRefererClassifier_ClassifySource_Call struct {
	*mock.Call
}

// ClassifySource is a helper method to define mock.On call
//   - refererStr string
func (_e *MockRefererClassifier_Expecter) ClassifySource(refererStr interface{}) *MockRefererClassifier_ClassifySource_Call {
	return &MockRefererClassifier_ClassifySource_Call{Call: _e.mock.On("ClassifySource", refererStr)}
}

func (_c *MockRefererClassifier_ClassifySource_Call) Run(run func(refererStr string)) *MockRefererClassifier_ClassifySource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRefererClassifier_ClassifySource_Call) Return(s string) *MockRefererClassifier_ClassifySource_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockRefererClassifier_ClassifySource_Call) RunAndReturn(run func(refererStr string) string) *MockRefererClassifier_ClassifySource_Call {
	_c.Call.Return(run)
	return _c
}
