// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"go-shortener/ent/outboxmessage"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// OutboxMessage is the model entity for the OutboxMessage schema.
type OutboxMessage struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UUID holds the value of the "uuid" field.
	UUID string `json:"uuid,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload []byte `json:"payload,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]string `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OutboxMessage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case outboxmessage.FieldPayload, outboxmessage.FieldMetadata:
			values[i] = new([]byte)
		case outboxmessage.FieldID:
			values[i] = new(sql.NullInt64)
		case outboxmessage.FieldUUID:
			values[i] = new(sql.NullString)
		case outboxmessage.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OutboxMessage fields.
func (om *OutboxMessage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case outboxmessage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			om.ID = int(value.Int64)
		case outboxmessage.FieldUUID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field uuid", values[i])
			} else if value.Valid {
				om.UUID = value.String
			}
		case outboxmessage.FieldPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value != nil {
				om.Payload = *value
			}
		case outboxmessage.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &om.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case outboxmessage.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				om.CreatedAt = value.Time
			}
		default:
			om.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OutboxMessage.
// This includes values selected through modifiers, order, etc.
func (om *OutboxMessage) Value(name string) (ent.Value, error) {
	return om.selectValues.Get(name)
}

// Update returns a builder for updating this OutboxMessage.
// Note that you need to call OutboxMessage.Unwrap() before calling this method if this OutboxMessage
// was returned from a transaction, and the transaction was committed or rolled back.
func (om *OutboxMessage) Update() *OutboxMessageUpdateOne {
	return NewOutboxMessageClient(om.config).UpdateOne(om)
}

// Unwrap unwraps the OutboxMessage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (om *OutboxMessage) Unwrap() *OutboxMessage {
	_tx, ok := om.config.driver.(*txDriver)
	if !ok {
		panic("ent: OutboxMessage is not a transactional entity")
	}
	om.config.driver = _tx.drv
	return om
}

// String implements the fmt.Stringer.
func (om *OutboxMessage) String() string {
	var builder strings.Builder
	builder.WriteString("OutboxMessage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", om.ID))
	builder.WriteString("uuid=")
	builder.WriteString(om.UUID)
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(fmt.Sprintf("%v", om.Payload))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", om.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(om.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OutboxMessages is a parsable slice of OutboxMessage.
type OutboxMessages []*OutboxMessage
