// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-shortener/ent/outboxmessage"
	"go-shortener/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OutboxMessageUpdate is the builder for updating OutboxMessage entities.
type OutboxMessageUpdate struct {
	config
	hooks    []Hook
	mutation *OutboxMessageMutation
}

// Where appends a list predicates to the OutboxMessageUpdate builder.
func (omu *OutboxMessageUpdate) Where(ps ...predicate.OutboxMessage) *OutboxMessageUpdate {
	omu.mutation.Where(ps...)
	return omu
}

// SetUUID sets the "uuid" field.
func (omu *OutboxMessageUpdate) SetUUID(s string) *OutboxMessageUpdate {
	omu.mutation.SetUUID(s)
	return omu
}

// SetNillableUUID sets the "uuid" field if the given value is not nil.
func (omu *OutboxMessageUpdate) SetNillableUUID(s *string) *OutboxMessageUpdate {
	if s != nil {
		omu.SetUUID(*s)
	}
	return omu
}

// SetPayload sets the "payload" field.
func (omu *OutboxMessageUpdate) SetPayload(b []byte) *OutboxMessageUpdate {
	omu.mutation.SetPayload(b)
	return omu
}

// SetMetadata sets the "metadata" field.
func (omu *OutboxMessageUpdate) SetMetadata(m map[string]string) *OutboxMessageUpdate {
	omu.mutation.SetMetadata(m)
	return omu
}

// ClearMetadata clears the value of the "metadata" field.
func (omu *OutboxMessageUpdate) ClearMetadata() *OutboxMessageUpdate {
	omu.mutation.ClearMetadata()
	return omu
}

// Mutation returns the OutboxMessageMutation object of the builder.
func (omu *OutboxMessageUpdate) Mutation() *OutboxMessageMutation {
	return omu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (omu *OutboxMessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, omu.sqlSave, omu.mutation, omu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (omu *OutboxMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := omu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (omu *OutboxMessageUpdate) Exec(ctx context.Context) error {
	_, err := omu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (omu *OutboxMessageUpdate) ExecX(ctx context.Context) {
	if err := omu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (omu *OutboxMessageUpdate) check() error {
	if v, ok := omu.mutation.UUID(); ok {
		if err := outboxmessage.UUIDValidator(v); err != nil {
			return &ValidationError{Name: "uuid", err: fmt.Errorf(`ent: validator failed for field "OutboxMessage.uuid": %w`, err)}
		}
	}
	if v, ok := omu.mutation.Payload(); ok {
		if err := outboxmessage.PayloadValidator(v); err != nil {
			return &ValidationError{Name: "payload", err: fmt.Errorf(`ent: validator failed for field "OutboxMessage.payload": %w`, err)}
		}
	}
	return nil
}

func (omu *OutboxMessageUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := omu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(outboxmessage.Table, outboxmessage.Columns, sqlgraph.NewFieldSpec(outboxmessage.FieldID, field.TypeInt))
	if ps := omu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := omu.mutation.UUID(); ok {
		_spec.SetField(outboxmessage.FieldUUID, field.TypeString, value)
	}
	if value, ok := omu.mutation.Payload(); ok {
		_spec.SetField(outboxmessage.FieldPayload, field.TypeBytes, value)
	}
	if value, ok := omu.mutation.Metadata(); ok {
		_spec.SetField(outboxmessage.FieldMetadata, field.TypeJSON, value)
	}
	if omu.mutation.MetadataCleared() {
		_spec.ClearField(outboxmessage.FieldMetadata, field.TypeJSON)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, omu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{outboxmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	omu.mutation.done = true
	return n, nil
}

// OutboxMessageUpdateOne is the builder for updating a single OutboxMessage entity.
type OutboxMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OutboxMessageMutation
}

// SetUUID sets the "uuid" field.
func (omuo *OutboxMessageUpdateOne) SetUUID(s string) *OutboxMessageUpdateOne {
	omuo.mutation.SetUUID(s)
	return omuo
}

// SetNillableUUID sets the "uuid" field if the given value is not nil.
func (omuo *OutboxMessageUpdateOne) SetNillableUUID(s *string) *OutboxMessageUpdateOne {
	if s != nil {
		omuo.SetUUID(*s)
	}
	return omuo
}

// SetPayload sets the "payload" field.
func (omuo *OutboxMessageUpdateOne) SetPayload(b []byte) *OutboxMessageUpdateOne {
	omuo.mutation.SetPayload(b)
	return omuo
}

// SetMetadata sets the "metadata" field.
func (omuo *OutboxMessageUpdateOne) SetMetadata(m map[string]string) *OutboxMessageUpdateOne {
	omuo.mutation.SetMetadata(m)
	return omuo
}

// ClearMetadata clears the value of the "metadata" field.
func (omuo *OutboxMessageUpdateOne) ClearMetadata() *OutboxMessageUpdateOne {
	omuo.mutation.ClearMetadata()
	return omuo
}

// Mutation returns the OutboxMessageMutation object of the builder.
func (omuo *OutboxMessageUpdateOne) Mutation() *OutboxMessageMutation {
	return omuo.mutation
}

// Where appends a list predicates to the OutboxMessageUpdate builder.
func (omuo *OutboxMessageUpdateOne) Where(ps ...predicate.OutboxMessage) *OutboxMessageUpdateOne {
	omuo.mutation.Where(ps...)
	return omuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (omuo *OutboxMessageUpdateOne) Select(field string, fields ...string) *OutboxMessageUpdateOne {
	omuo.fields = append([]string{field}, fields...)
	return omuo
}

// Save executes the query and returns the updated OutboxMessage entity.
func (omuo *OutboxMessageUpdateOne) Save(ctx context.Context) (*OutboxMessage, error) {
	return withHooks(ctx, omuo.sqlSave, omuo.mutation, omuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (omuo *OutboxMessageUpdateOne) SaveX(ctx context.Context) *OutboxMessage {
	node, err := omuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (omuo *OutboxMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := omuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (omuo *OutboxMessageUpdateOne) ExecX(ctx context.Context) {
	if err := omuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (omuo *OutboxMessageUpdateOne) check() error {
	if v, ok := omuo.mutation.UUID(); ok {
		if err := outboxmessage.UUIDValidator(v); err != nil {
			return &ValidationError{Name: "uuid", err: fmt.Errorf(`ent: validator failed for field "OutboxMessage.uuid": %w`, err)}
		}
	}
	if v, ok := omuo.mutation.Payload(); ok {
		if err := outboxmessage.PayloadValidator(v); err != nil {
			return &ValidationError{Name: "payload", err: fmt.Errorf(`ent: validator failed for field "OutboxMessage.payload": %w`, err)}
		}
	}
	return nil
}

func (omuo *OutboxMessageUpdateOne) sqlSave(ctx context.Context) (_node *OutboxMessage, err error) {
	if err := omuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(outboxmessage.Table, outboxmessage.Columns, sqlgraph.NewFieldSpec(outboxmessage.FieldID, field.TypeInt))
	id, ok := omuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OutboxMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := omuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, outboxmessage.FieldID)
		for _, f := range fields {
			if !outboxmessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != outboxmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := omuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := omuo.mutation.UUID(); ok {
		_spec.SetField(outboxmessage.FieldUUID, field.TypeString, value)
	}
	if value, ok := omuo.mutation.Payload(); ok {
		_spec.SetField(outboxmessage.FieldPayload, field.TypeBytes, value)
	}
	if value, ok := omuo.mutation.Metadata(); ok {
		_spec.SetField(outboxmessage.FieldMetadata, field.TypeJSON, value)
	}
	if omuo.mutation.MetadataCleared() {
		_spec.ClearField(outboxmessage.FieldMetadata, field.TypeJSON)
	}
	_node = &OutboxMessage{config: omuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, omuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{outboxmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	omuo.mutation.done = true
	return _node, nil
}
