// Code generated by ent, DO NOT EDIT.

package ent

import (
	"go-shortener/ent/schema"
	"go-shortener/ent/url"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	urlFields := schema.URL{}.Fields()
	_ = urlFields
	// urlDescShortCode is the schema descriptor for short_code field.
	urlDescShortCode := urlFields[0].Descriptor()
	// url.ShortCodeValidator is a validator for the "short_code" field. It is called by the builders before save.
	url.ShortCodeValidator = func() func(string) error {
		validators := urlDescShortCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(short_code string) error {
			for _, fn := range fns {
				if err := fn(short_code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// urlDescOriginalURL is the schema descriptor for original_url field.
	urlDescOriginalURL := urlFields[1].Descriptor()
	// url.OriginalURLValidator is a validator for the "original_url" field. It is called by the builders before save.
	url.OriginalURLValidator = func() func(string) error {
		validators := urlDescOriginalURL.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(original_url string) error {
			for _, fn := range fns {
				if err := fn(original_url); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// urlDescClickCount is the schema descriptor for click_count field.
	urlDescClickCount := urlFields[2].Descriptor()
	// url.DefaultClickCount holds the default value on creation for the click_count field.
	url.DefaultClickCount = urlDescClickCount.Default.(int64)
	// url.ClickCountValidator is a validator for the "click_count" field. It is called by the builders before save.
	url.ClickCountValidator = urlDescClickCount.Validators[0].(func(int64) error)
	// urlDescCreatedAt is the schema descriptor for created_at field.
	urlDescCreatedAt := urlFields[4].Descriptor()
	// url.DefaultCreatedAt holds the default value on creation for the created_at field.
	url.DefaultCreatedAt = urlDescCreatedAt.Default.(func() time.Time)
	// urlDescUpdatedAt is the schema descriptor for updated_at field.
	urlDescUpdatedAt := urlFields[5].Descriptor()
	// url.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	url.DefaultUpdatedAt = urlDescUpdatedAt.Default.(func() time.Time)
	// url.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	url.UpdateDefaultUpdatedAt = urlDescUpdatedAt.UpdateDefault.(func() time.Time)
}
