// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-shortener/ent/url"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// URL is the model entity for the URL schema.
type URL struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// The unique short code for the URL
	ShortCode string `json:"short_code,omitempty"`
	// The original long URL
	OriginalURL string `json:"original_url,omitempty"`
	// Number of times this URL has been accessed
	ClickCount int64 `json:"click_count,omitempty"`
	// Optional expiration time for the URL
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// When the URL was created
	CreatedAt time.Time `json:"created_at,omitempty"`
	// When the URL was last updated
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*URL) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case url.FieldID, url.FieldClickCount:
			values[i] = new(sql.NullInt64)
		case url.FieldShortCode, url.FieldOriginalURL:
			values[i] = new(sql.NullString)
		case url.FieldExpiresAt, url.FieldCreatedAt, url.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the URL fields.
func (_m *URL) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case url.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case url.FieldShortCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field short_code", values[i])
			} else if value.Valid {
				_m.ShortCode = value.String
			}
		case url.FieldOriginalURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field original_url", values[i])
			} else if value.Valid {
				_m.OriginalURL = value.String
			}
		case url.FieldClickCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field click_count", values[i])
			} else if value.Valid {
				_m.ClickCount = value.Int64
			}
		case url.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case url.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case url.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the URL.
// This includes values selected through modifiers, order, etc.
func (_m *URL) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this URL.
// Note that you need to call URL.Unwrap() before calling this method if this URL
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *URL) Update() *URLUpdateOne {
	return NewURLClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the URL entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *URL) Unwrap() *URL {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: URL is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *URL) String() string {
	var builder strings.Builder
	builder.WriteString("URL(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("short_code=")
	builder.WriteString(_m.ShortCode)
	builder.WriteString(", ")
	builder.WriteString("original_url=")
	builder.WriteString(_m.OriginalURL)
	builder.WriteString(", ")
	builder.WriteString("click_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClickCount))
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// URLs is a parsable slice of URL.
type URLs []*URL
