// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-shortener/ent/url"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// URL is the model entity for the URL schema.
type URL struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// The unique short code for the URL
	ShortCode string `json:"short_code,omitempty"`
	// The original long URL
	OriginalURL string `json:"original_url,omitempty"`
	// Number of times this URL has been accessed
	ClickCount int64 `json:"click_count,omitempty"`
	// Optional expiration time for the URL
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// When the URL was created
	CreatedAt time.Time `json:"created_at,omitempty"`
	// When the URL was last updated
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*URL) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case url.FieldID, url.FieldClickCount:
			values[i] = new(sql.NullInt64)
		case url.FieldShortCode, url.FieldOriginalURL:
			values[i] = new(sql.NullString)
		case url.FieldExpiresAt, url.FieldCreatedAt, url.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the URL fields.
func (u *URL) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case url.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			u.ID = int(value.Int64)
		case url.FieldShortCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field short_code", values[i])
			} else if value.Valid {
				u.ShortCode = value.String
			}
		case url.FieldOriginalURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field original_url", values[i])
			} else if value.Valid {
				u.OriginalURL = value.String
			}
		case url.FieldClickCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field click_count", values[i])
			} else if value.Valid {
				u.ClickCount = value.Int64
			}
		case url.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				u.ExpiresAt = new(time.Time)
				*u.ExpiresAt = value.Time
			}
		case url.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				u.CreatedAt = value.Time
			}
		case url.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				u.UpdatedAt = value.Time
			}
		default:
			u.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the URL.
// This includes values selected through modifiers, order, etc.
func (u *URL) Value(name string) (ent.Value, error) {
	return u.selectValues.Get(name)
}

// Update returns a builder for updating this URL.
// Note that you need to call URL.Unwrap() before calling this method if this URL
// was returned from a transaction, and the transaction was committed or rolled back.
func (u *URL) Update() *URLUpdateOne {
	return NewURLClient(u.config).UpdateOne(u)
}

// Unwrap unwraps the URL entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (u *URL) Unwrap() *URL {
	_tx, ok := u.config.driver.(*txDriver)
	if !ok {
		panic("ent: URL is not a transactional entity")
	}
	u.config.driver = _tx.drv
	return u
}

// String implements the fmt.Stringer.
func (u *URL) String() string {
	var builder strings.Builder
	builder.WriteString("URL(")
	builder.WriteString(fmt.Sprintf("id=%v, ", u.ID))
	builder.WriteString("short_code=")
	builder.WriteString(u.ShortCode)
	builder.WriteString(", ")
	builder.WriteString("original_url=")
	builder.WriteString(u.OriginalURL)
	builder.WriteString(", ")
	builder.WriteString("click_count=")
	builder.WriteString(fmt.Sprintf("%v", u.ClickCount))
	builder.WriteString(", ")
	if v := u.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(u.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(u.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// URLs is a parsable slice of URL.
type URLs []*URL
