// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-shortener/ent/predicate"
	"go-shortener/ent/url"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// URLUpdate is the builder for updating URL entities.
type URLUpdate struct {
	config
	hooks    []Hook
	mutation *URLMutation
}

// Where appends a list predicates to the URLUpdate builder.
func (uu *URLUpdate) Where(ps ...predicate.URL) *URLUpdate {
	uu.mutation.Where(ps...)
	return uu
}

// SetShortCode sets the "short_code" field.
func (uu *URLUpdate) SetShortCode(s string) *URLUpdate {
	uu.mutation.SetShortCode(s)
	return uu
}

// SetNillableShortCode sets the "short_code" field if the given value is not nil.
func (uu *URLUpdate) SetNillableShortCode(s *string) *URLUpdate {
	if s != nil {
		uu.SetShortCode(*s)
	}
	return uu
}

// SetOriginalURL sets the "original_url" field.
func (uu *URLUpdate) SetOriginalURL(s string) *URLUpdate {
	uu.mutation.SetOriginalURL(s)
	return uu
}

// SetNillableOriginalURL sets the "original_url" field if the given value is not nil.
func (uu *URLUpdate) SetNillableOriginalURL(s *string) *URLUpdate {
	if s != nil {
		uu.SetOriginalURL(*s)
	}
	return uu
}

// SetClickCount sets the "click_count" field.
func (uu *URLUpdate) SetClickCount(i int64) *URLUpdate {
	uu.mutation.ResetClickCount()
	uu.mutation.SetClickCount(i)
	return uu
}

// SetNillableClickCount sets the "click_count" field if the given value is not nil.
func (uu *URLUpdate) SetNillableClickCount(i *int64) *URLUpdate {
	if i != nil {
		uu.SetClickCount(*i)
	}
	return uu
}

// AddClickCount adds i to the "click_count" field.
func (uu *URLUpdate) AddClickCount(i int64) *URLUpdate {
	uu.mutation.AddClickCount(i)
	return uu
}

// SetExpiresAt sets the "expires_at" field.
func (uu *URLUpdate) SetExpiresAt(t time.Time) *URLUpdate {
	uu.mutation.SetExpiresAt(t)
	return uu
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (uu *URLUpdate) SetNillableExpiresAt(t *time.Time) *URLUpdate {
	if t != nil {
		uu.SetExpiresAt(*t)
	}
	return uu
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (uu *URLUpdate) ClearExpiresAt() *URLUpdate {
	uu.mutation.ClearExpiresAt()
	return uu
}

// SetUpdatedAt sets the "updated_at" field.
func (uu *URLUpdate) SetUpdatedAt(t time.Time) *URLUpdate {
	uu.mutation.SetUpdatedAt(t)
	return uu
}

// Mutation returns the URLMutation object of the builder.
func (uu *URLUpdate) Mutation() *URLMutation {
	return uu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uu *URLUpdate) Save(ctx context.Context) (int, error) {
	uu.defaults()
	return withHooks(ctx, uu.sqlSave, uu.mutation, uu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uu *URLUpdate) SaveX(ctx context.Context) int {
	affected, err := uu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uu *URLUpdate) Exec(ctx context.Context) error {
	_, err := uu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uu *URLUpdate) ExecX(ctx context.Context) {
	if err := uu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uu *URLUpdate) defaults() {
	if _, ok := uu.mutation.UpdatedAt(); !ok {
		v := url.UpdateDefaultUpdatedAt()
		uu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uu *URLUpdate) check() error {
	if v, ok := uu.mutation.ShortCode(); ok {
		if err := url.ShortCodeValidator(v); err != nil {
			return &ValidationError{Name: "short_code", err: fmt.Errorf(`ent: validator failed for field "URL.short_code": %w`, err)}
		}
	}
	if v, ok := uu.mutation.OriginalURL(); ok {
		if err := url.OriginalURLValidator(v); err != nil {
			return &ValidationError{Name: "original_url", err: fmt.Errorf(`ent: validator failed for field "URL.original_url": %w`, err)}
		}
	}
	if v, ok := uu.mutation.ClickCount(); ok {
		if err := url.ClickCountValidator(v); err != nil {
			return &ValidationError{Name: "click_count", err: fmt.Errorf(`ent: validator failed for field "URL.click_count": %w`, err)}
		}
	}
	return nil
}

func (uu *URLUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := uu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(url.Table, url.Columns, sqlgraph.NewFieldSpec(url.FieldID, field.TypeInt))
	if ps := uu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uu.mutation.ShortCode(); ok {
		_spec.SetField(url.FieldShortCode, field.TypeString, value)
	}
	if value, ok := uu.mutation.OriginalURL(); ok {
		_spec.SetField(url.FieldOriginalURL, field.TypeString, value)
	}
	if value, ok := uu.mutation.ClickCount(); ok {
		_spec.SetField(url.FieldClickCount, field.TypeInt64, value)
	}
	if value, ok := uu.mutation.AddedClickCount(); ok {
		_spec.AddField(url.FieldClickCount, field.TypeInt64, value)
	}
	if value, ok := uu.mutation.ExpiresAt(); ok {
		_spec.SetField(url.FieldExpiresAt, field.TypeTime, value)
	}
	if uu.mutation.ExpiresAtCleared() {
		_spec.ClearField(url.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := uu.mutation.UpdatedAt(); ok {
		_spec.SetField(url.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{url.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uu.mutation.done = true
	return n, nil
}

// URLUpdateOne is the builder for updating a single URL entity.
type URLUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *URLMutation
}

// SetShortCode sets the "short_code" field.
func (uuo *URLUpdateOne) SetShortCode(s string) *URLUpdateOne {
	uuo.mutation.SetShortCode(s)
	return uuo
}

// SetNillableShortCode sets the "short_code" field if the given value is not nil.
func (uuo *URLUpdateOne) SetNillableShortCode(s *string) *URLUpdateOne {
	if s != nil {
		uuo.SetShortCode(*s)
	}
	return uuo
}

// SetOriginalURL sets the "original_url" field.
func (uuo *URLUpdateOne) SetOriginalURL(s string) *URLUpdateOne {
	uuo.mutation.SetOriginalURL(s)
	return uuo
}

// SetNillableOriginalURL sets the "original_url" field if the given value is not nil.
func (uuo *URLUpdateOne) SetNillableOriginalURL(s *string) *URLUpdateOne {
	if s != nil {
		uuo.SetOriginalURL(*s)
	}
	return uuo
}

// SetClickCount sets the "click_count" field.
func (uuo *URLUpdateOne) SetClickCount(i int64) *URLUpdateOne {
	uuo.mutation.ResetClickCount()
	uuo.mutation.SetClickCount(i)
	return uuo
}

// SetNillableClickCount sets the "click_count" field if the given value is not nil.
func (uuo *URLUpdateOne) SetNillableClickCount(i *int64) *URLUpdateOne {
	if i != nil {
		uuo.SetClickCount(*i)
	}
	return uuo
}

// AddClickCount adds i to the "click_count" field.
func (uuo *URLUpdateOne) AddClickCount(i int64) *URLUpdateOne {
	uuo.mutation.AddClickCount(i)
	return uuo
}

// SetExpiresAt sets the "expires_at" field.
func (uuo *URLUpdateOne) SetExpiresAt(t time.Time) *URLUpdateOne {
	uuo.mutation.SetExpiresAt(t)
	return uuo
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (uuo *URLUpdateOne) SetNillableExpiresAt(t *time.Time) *URLUpdateOne {
	if t != nil {
		uuo.SetExpiresAt(*t)
	}
	return uuo
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (uuo *URLUpdateOne) ClearExpiresAt() *URLUpdateOne {
	uuo.mutation.ClearExpiresAt()
	return uuo
}

// SetUpdatedAt sets the "updated_at" field.
func (uuo *URLUpdateOne) SetUpdatedAt(t time.Time) *URLUpdateOne {
	uuo.mutation.SetUpdatedAt(t)
	return uuo
}

// Mutation returns the URLMutation object of the builder.
func (uuo *URLUpdateOne) Mutation() *URLMutation {
	return uuo.mutation
}

// Where appends a list predicates to the URLUpdate builder.
func (uuo *URLUpdateOne) Where(ps ...predicate.URL) *URLUpdateOne {
	uuo.mutation.Where(ps...)
	return uuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uuo *URLUpdateOne) Select(field string, fields ...string) *URLUpdateOne {
	uuo.fields = append([]string{field}, fields...)
	return uuo
}

// Save executes the query and returns the updated URL entity.
func (uuo *URLUpdateOne) Save(ctx context.Context) (*URL, error) {
	uuo.defaults()
	return withHooks(ctx, uuo.sqlSave, uuo.mutation, uuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uuo *URLUpdateOne) SaveX(ctx context.Context) *URL {
	node, err := uuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uuo *URLUpdateOne) Exec(ctx context.Context) error {
	_, err := uuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uuo *URLUpdateOne) ExecX(ctx context.Context) {
	if err := uuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uuo *URLUpdateOne) defaults() {
	if _, ok := uuo.mutation.UpdatedAt(); !ok {
		v := url.UpdateDefaultUpdatedAt()
		uuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uuo *URLUpdateOne) check() error {
	if v, ok := uuo.mutation.ShortCode(); ok {
		if err := url.ShortCodeValidator(v); err != nil {
			return &ValidationError{Name: "short_code", err: fmt.Errorf(`ent: validator failed for field "URL.short_code": %w`, err)}
		}
	}
	if v, ok := uuo.mutation.OriginalURL(); ok {
		if err := url.OriginalURLValidator(v); err != nil {
			return &ValidationError{Name: "original_url", err: fmt.Errorf(`ent: validator failed for field "URL.original_url": %w`, err)}
		}
	}
	if v, ok := uuo.mutation.ClickCount(); ok {
		if err := url.ClickCountValidator(v); err != nil {
			return &ValidationError{Name: "click_count", err: fmt.Errorf(`ent: validator failed for field "URL.click_count": %w`, err)}
		}
	}
	return nil
}

func (uuo *URLUpdateOne) sqlSave(ctx context.Context) (_node *URL, err error) {
	if err := uuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(url.Table, url.Columns, sqlgraph.NewFieldSpec(url.FieldID, field.TypeInt))
	id, ok := uuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "URL.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, url.FieldID)
		for _, f := range fields {
			if !url.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != url.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uuo.mutation.ShortCode(); ok {
		_spec.SetField(url.FieldShortCode, field.TypeString, value)
	}
	if value, ok := uuo.mutation.OriginalURL(); ok {
		_spec.SetField(url.FieldOriginalURL, field.TypeString, value)
	}
	if value, ok := uuo.mutation.ClickCount(); ok {
		_spec.SetField(url.FieldClickCount, field.TypeInt64, value)
	}
	if value, ok := uuo.mutation.AddedClickCount(); ok {
		_spec.AddField(url.FieldClickCount, field.TypeInt64, value)
	}
	if value, ok := uuo.mutation.ExpiresAt(); ok {
		_spec.SetField(url.FieldExpiresAt, field.TypeTime, value)
	}
	if uuo.mutation.ExpiresAtCleared() {
		_spec.ClearField(url.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := uuo.mutation.UpdatedAt(); ok {
		_spec.SetField(url.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &URL{config: uuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{url.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uuo.mutation.done = true
	return _node, nil
}
