// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-shortener/ent/url"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// URLCreate is the builder for creating a URL entity.
type URLCreate struct {
	config
	mutation *URLMutation
	hooks    []Hook
}

// SetShortCode sets the "short_code" field.
func (uc *URLCreate) SetShortCode(s string) *URLCreate {
	uc.mutation.SetShortCode(s)
	return uc
}

// SetOriginalURL sets the "original_url" field.
func (uc *URLCreate) SetOriginalURL(s string) *URLCreate {
	uc.mutation.SetOriginalURL(s)
	return uc
}

// SetClickCount sets the "click_count" field.
func (uc *URLCreate) SetClickCount(i int64) *URLCreate {
	uc.mutation.SetClickCount(i)
	return uc
}

// SetNillableClickCount sets the "click_count" field if the given value is not nil.
func (uc *URLCreate) SetNillableClickCount(i *int64) *URLCreate {
	if i != nil {
		uc.SetClickCount(*i)
	}
	return uc
}

// SetExpiresAt sets the "expires_at" field.
func (uc *URLCreate) SetExpiresAt(t time.Time) *URLCreate {
	uc.mutation.SetExpiresAt(t)
	return uc
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (uc *URLCreate) SetNillableExpiresAt(t *time.Time) *URLCreate {
	if t != nil {
		uc.SetExpiresAt(*t)
	}
	return uc
}

// SetCreatedAt sets the "created_at" field.
func (uc *URLCreate) SetCreatedAt(t time.Time) *URLCreate {
	uc.mutation.SetCreatedAt(t)
	return uc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (uc *URLCreate) SetNillableCreatedAt(t *time.Time) *URLCreate {
	if t != nil {
		uc.SetCreatedAt(*t)
	}
	return uc
}

// SetUpdatedAt sets the "updated_at" field.
func (uc *URLCreate) SetUpdatedAt(t time.Time) *URLCreate {
	uc.mutation.SetUpdatedAt(t)
	return uc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (uc *URLCreate) SetNillableUpdatedAt(t *time.Time) *URLCreate {
	if t != nil {
		uc.SetUpdatedAt(*t)
	}
	return uc
}

// Mutation returns the URLMutation object of the builder.
func (uc *URLCreate) Mutation() *URLMutation {
	return uc.mutation
}

// Save creates the URL in the database.
func (uc *URLCreate) Save(ctx context.Context) (*URL, error) {
	uc.defaults()
	return withHooks(ctx, uc.sqlSave, uc.mutation, uc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (uc *URLCreate) SaveX(ctx context.Context) *URL {
	v, err := uc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uc *URLCreate) Exec(ctx context.Context) error {
	_, err := uc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uc *URLCreate) ExecX(ctx context.Context) {
	if err := uc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uc *URLCreate) defaults() {
	if _, ok := uc.mutation.ClickCount(); !ok {
		v := url.DefaultClickCount
		uc.mutation.SetClickCount(v)
	}
	if _, ok := uc.mutation.CreatedAt(); !ok {
		v := url.DefaultCreatedAt()
		uc.mutation.SetCreatedAt(v)
	}
	if _, ok := uc.mutation.UpdatedAt(); !ok {
		v := url.DefaultUpdatedAt()
		uc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uc *URLCreate) check() error {
	if _, ok := uc.mutation.ShortCode(); !ok {
		return &ValidationError{Name: "short_code", err: errors.New(`ent: missing required field "URL.short_code"`)}
	}
	if v, ok := uc.mutation.ShortCode(); ok {
		if err := url.ShortCodeValidator(v); err != nil {
			return &ValidationError{Name: "short_code", err: fmt.Errorf(`ent: validator failed for field "URL.short_code": %w`, err)}
		}
	}
	if _, ok := uc.mutation.OriginalURL(); !ok {
		return &ValidationError{Name: "original_url", err: errors.New(`ent: missing required field "URL.original_url"`)}
	}
	if v, ok := uc.mutation.OriginalURL(); ok {
		if err := url.OriginalURLValidator(v); err != nil {
			return &ValidationError{Name: "original_url", err: fmt.Errorf(`ent: validator failed for field "URL.original_url": %w`, err)}
		}
	}
	if _, ok := uc.mutation.ClickCount(); !ok {
		return &ValidationError{Name: "click_count", err: errors.New(`ent: missing required field "URL.click_count"`)}
	}
	if v, ok := uc.mutation.ClickCount(); ok {
		if err := url.ClickCountValidator(v); err != nil {
			return &ValidationError{Name: "click_count", err: fmt.Errorf(`ent: validator failed for field "URL.click_count": %w`, err)}
		}
	}
	if _, ok := uc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "URL.created_at"`)}
	}
	if _, ok := uc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "URL.updated_at"`)}
	}
	return nil
}

func (uc *URLCreate) sqlSave(ctx context.Context) (*URL, error) {
	if err := uc.check(); err != nil {
		return nil, err
	}
	_node, _spec := uc.createSpec()
	if err := sqlgraph.CreateNode(ctx, uc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	uc.mutation.id = &_node.ID
	uc.mutation.done = true
	return _node, nil
}

func (uc *URLCreate) createSpec() (*URL, *sqlgraph.CreateSpec) {
	var (
		_node = &URL{config: uc.config}
		_spec = sqlgraph.NewCreateSpec(url.Table, sqlgraph.NewFieldSpec(url.FieldID, field.TypeInt))
	)
	if value, ok := uc.mutation.ShortCode(); ok {
		_spec.SetField(url.FieldShortCode, field.TypeString, value)
		_node.ShortCode = value
	}
	if value, ok := uc.mutation.OriginalURL(); ok {
		_spec.SetField(url.FieldOriginalURL, field.TypeString, value)
		_node.OriginalURL = value
	}
	if value, ok := uc.mutation.ClickCount(); ok {
		_spec.SetField(url.FieldClickCount, field.TypeInt64, value)
		_node.ClickCount = value
	}
	if value, ok := uc.mutation.ExpiresAt(); ok {
		_spec.SetField(url.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := uc.mutation.CreatedAt(); ok {
		_spec.SetField(url.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := uc.mutation.UpdatedAt(); ok {
		_spec.SetField(url.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// URLCreateBulk is the builder for creating many URL entities in bulk.
type URLCreateBulk struct {
	config
	err      error
	builders []*URLCreate
}

// Save creates the URL entities in the database.
func (ucb *URLCreateBulk) Save(ctx context.Context) ([]*URL, error) {
	if ucb.err != nil {
		return nil, ucb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ucb.builders))
	nodes := make([]*URL, len(ucb.builders))
	mutators := make([]Mutator, len(ucb.builders))
	for i := range ucb.builders {
		func(i int, root context.Context) {
			builder := ucb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*URLMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ucb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ucb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ucb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ucb *URLCreateBulk) SaveX(ctx context.Context) []*URL {
	v, err := ucb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ucb *URLCreateBulk) Exec(ctx context.Context) error {
	_, err := ucb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ucb *URLCreateBulk) ExecX(ctx context.Context) {
	if err := ucb.Exec(ctx); err != nil {
		panic(err)
	}
}
