// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-shortener/ent/predicate"
	"go-shortener/ent/url"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// URLUpdate is the builder for updating URL entities.
type URLUpdate struct {
	config
	hooks    []Hook
	mutation *URLMutation
}

// Where appends a list predicates to the URLUpdate builder.
func (_u *URLUpdate) Where(ps ...predicate.URL) *URLUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetShortCode sets the "short_code" field.
func (_u *URLUpdate) SetShortCode(v string) *URLUpdate {
	_u.mutation.SetShortCode(v)
	return _u
}

// SetNillableShortCode sets the "short_code" field if the given value is not nil.
func (_u *URLUpdate) SetNillableShortCode(v *string) *URLUpdate {
	if v != nil {
		_u.SetShortCode(*v)
	}
	return _u
}

// SetOriginalURL sets the "original_url" field.
func (_u *URLUpdate) SetOriginalURL(v string) *URLUpdate {
	_u.mutation.SetOriginalURL(v)
	return _u
}

// SetNillableOriginalURL sets the "original_url" field if the given value is not nil.
func (_u *URLUpdate) SetNillableOriginalURL(v *string) *URLUpdate {
	if v != nil {
		_u.SetOriginalURL(*v)
	}
	return _u
}

// SetClickCount sets the "click_count" field.
func (_u *URLUpdate) SetClickCount(v int64) *URLUpdate {
	_u.mutation.ResetClickCount()
	_u.mutation.SetClickCount(v)
	return _u
}

// SetNillableClickCount sets the "click_count" field if the given value is not nil.
func (_u *URLUpdate) SetNillableClickCount(v *int64) *URLUpdate {
	if v != nil {
		_u.SetClickCount(*v)
	}
	return _u
}

// AddClickCount adds value to the "click_count" field.
func (_u *URLUpdate) AddClickCount(v int64) *URLUpdate {
	_u.mutation.AddClickCount(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *URLUpdate) SetExpiresAt(v time.Time) *URLUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *URLUpdate) SetNillableExpiresAt(v *time.Time) *URLUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *URLUpdate) ClearExpiresAt() *URLUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *URLUpdate) SetUpdatedAt(v time.Time) *URLUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the URLMutation object of the builder.
func (_u *URLUpdate) Mutation() *URLMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *URLUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *URLUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *URLUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *URLUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *URLUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := url.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *URLUpdate) check() error {
	if v, ok := _u.mutation.ShortCode(); ok {
		if err := url.ShortCodeValidator(v); err != nil {
			return &ValidationError{Name: "short_code", err: fmt.Errorf(`ent: validator failed for field "URL.short_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OriginalURL(); ok {
		if err := url.OriginalURLValidator(v); err != nil {
			return &ValidationError{Name: "original_url", err: fmt.Errorf(`ent: validator failed for field "URL.original_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClickCount(); ok {
		if err := url.ClickCountValidator(v); err != nil {
			return &ValidationError{Name: "click_count", err: fmt.Errorf(`ent: validator failed for field "URL.click_count": %w`, err)}
		}
	}
	return nil
}

func (_u *URLUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(url.Table, url.Columns, sqlgraph.NewFieldSpec(url.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ShortCode(); ok {
		_spec.SetField(url.FieldShortCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginalURL(); ok {
		_spec.SetField(url.FieldOriginalURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClickCount(); ok {
		_spec.SetField(url.FieldClickCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedClickCount(); ok {
		_spec.AddField(url.FieldClickCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(url.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(url.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(url.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{url.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// URLUpdateOne is the builder for updating a single URL entity.
type URLUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *URLMutation
}

// SetShortCode sets the "short_code" field.
func (_u *URLUpdateOne) SetShortCode(v string) *URLUpdateOne {
	_u.mutation.SetShortCode(v)
	return _u
}

// SetNillableShortCode sets the "short_code" field if the given value is not nil.
func (_u *URLUpdateOne) SetNillableShortCode(v *string) *URLUpdateOne {
	if v != nil {
		_u.SetShortCode(*v)
	}
	return _u
}

// SetOriginalURL sets the "original_url" field.
func (_u *URLUpdateOne) SetOriginalURL(v string) *URLUpdateOne {
	_u.mutation.SetOriginalURL(v)
	return _u
}

// SetNillableOriginalURL sets the "original_url" field if the given value is not nil.
func (_u *URLUpdateOne) SetNillableOriginalURL(v *string) *URLUpdateOne {
	if v != nil {
		_u.SetOriginalURL(*v)
	}
	return _u
}

// SetClickCount sets the "click_count" field.
func (_u *URLUpdateOne) SetClickCount(v int64) *URLUpdateOne {
	_u.mutation.ResetClickCount()
	_u.mutation.SetClickCount(v)
	return _u
}

// SetNillableClickCount sets the "click_count" field if the given value is not nil.
func (_u *URLUpdateOne) SetNillableClickCount(v *int64) *URLUpdateOne {
	if v != nil {
		_u.SetClickCount(*v)
	}
	return _u
}

// AddClickCount adds value to the "click_count" field.
func (_u *URLUpdateOne) AddClickCount(v int64) *URLUpdateOne {
	_u.mutation.AddClickCount(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *URLUpdateOne) SetExpiresAt(v time.Time) *URLUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *URLUpdateOne) SetNillableExpiresAt(v *time.Time) *URLUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *URLUpdateOne) ClearExpiresAt() *URLUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *URLUpdateOne) SetUpdatedAt(v time.Time) *URLUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the URLMutation object of the builder.
func (_u *URLUpdateOne) Mutation() *URLMutation {
	return _u.mutation
}

// Where appends a list predicates to the URLUpdate builder.
func (_u *URLUpdateOne) Where(ps ...predicate.URL) *URLUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *URLUpdateOne) Select(field string, fields ...string) *URLUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated URL entity.
func (_u *URLUpdateOne) Save(ctx context.Context) (*URL, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *URLUpdateOne) SaveX(ctx context.Context) *URL {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *URLUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *URLUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *URLUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := url.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *URLUpdateOne) check() error {
	if v, ok := _u.mutation.ShortCode(); ok {
		if err := url.ShortCodeValidator(v); err != nil {
			return &ValidationError{Name: "short_code", err: fmt.Errorf(`ent: validator failed for field "URL.short_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OriginalURL(); ok {
		if err := url.OriginalURLValidator(v); err != nil {
			return &ValidationError{Name: "original_url", err: fmt.Errorf(`ent: validator failed for field "URL.original_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClickCount(); ok {
		if err := url.ClickCountValidator(v); err != nil {
			return &ValidationError{Name: "click_count", err: fmt.Errorf(`ent: validator failed for field "URL.click_count": %w`, err)}
		}
	}
	return nil
}

func (_u *URLUpdateOne) sqlSave(ctx context.Context) (_node *URL, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(url.Table, url.Columns, sqlgraph.NewFieldSpec(url.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "URL.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, url.FieldID)
		for _, f := range fields {
			if !url.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != url.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ShortCode(); ok {
		_spec.SetField(url.FieldShortCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginalURL(); ok {
		_spec.SetField(url.FieldOriginalURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClickCount(); ok {
		_spec.SetField(url.FieldClickCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedClickCount(); ok {
		_spec.AddField(url.FieldClickCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(url.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(url.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(url.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &URL{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{url.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
