// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"go-shortener/internal/biz"
	"go-shortener/internal/conf"
	"go-shortener/internal/data"
	"go-shortener/internal/server"
	"go-shortener/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	urlRepository := data.NewURLRepo(dataData, logger)
	dispatcher := data.NewEventDispatcher(logger)
	unitOfWork := data.NewUnitOfWork(dataData, dispatcher, logger)
	urlUsecase := biz.NewURLUsecase(urlRepository, unitOfWork, logger)
	shortenerService := service.NewShortenerService(urlUsecase)
	grpcServer := server.NewGRPCServer(confServer, shortenerService, logger)
	httpServer := server.NewHTTPServer(confServer, shortenerService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
