// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-shortener/internal/urlservice/domain"
	"go-shortener/internal/urlservice/usecase"

	mock "github.com/stretchr/testify/mock"
)

// NewMockURLRepository creates a new instance of MockURLRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockURLRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockURLRepository {
	mock := &MockURLRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockURLRepository is an autogenerated mock type for the URLRepository type
type MockURLRepository struct {
	mock.Mock
}

type MockURLRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockURLRepository) EXPECT() *MockURLRepository_Expecter {
	return &MockURLRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type MockURLRepository
func (_mock *MockURLRepository) Count(ctx context.Context, params usecase.CountParams) (int64, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.CountParams) (int64, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.CountParams) int64); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, usecase.CountParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockURLRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockURLRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
//   - params usecase.CountParams
func (_e *MockURLRepository_Expecter) Count(ctx interface{}, params interface{}) *MockURLRepository_Count_Call {
	return &MockURLRepository_Count_Call{Call: _e.mock.On("Count", ctx, params)}
}

func (_c *MockURLRepository_Count_Call) Run(run func(ctx context.Context, params usecase.CountParams)) *MockURLRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 usecase.CountParams
		if args[1] != nil {
			arg1 = args[1].(usecase.CountParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockURLRepository_Count_Call) Return(n int64, err error) *MockURLRepository_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockURLRepository_Count_Call) RunAndReturn(run func(ctx context.Context, params usecase.CountParams) (int64, error)) *MockURLRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockURLRepository
func (_mock *MockURLRepository) Delete(ctx context.Context, shortCode string) error {
	ret := _mock.Called(ctx, shortCode)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, shortCode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockURLRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockURLRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - shortCode string
func (_e *MockURLRepository_Expecter) Delete(ctx interface{}, shortCode interface{}) *MockURLRepository_Delete_Call {
	return &MockURLRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, shortCode)}
}

func (_c *MockURLRepository_Delete_Call) Run(run func(ctx context.Context, shortCode string)) *MockURLRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockURLRepository_Delete_Call) Return(err error) *MockURLRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockURLRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, shortCode string) error) *MockURLRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockURLRepository
func (_mock *MockURLRepository) FindAll(ctx context.Context, params usecase.FindAllParams) ([]domain.URL, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.URL
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.FindAllParams) ([]domain.URL, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.FindAllParams) []domain.URL); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.URL)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, usecase.FindAllParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockURLRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockURLRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - params usecase.FindAllParams
func (_e *MockURLRepository_Expecter) FindAll(ctx interface{}, params interface{}) *MockURLRepository_FindAll_Call {
	return &MockURLRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, params)}
}

func (_c *MockURLRepository_FindAll_Call) Run(run func(ctx context.Context, params usecase.FindAllParams)) *MockURLRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 usecase.FindAllParams
		if args[1] != nil {
			arg1 = args[1].(usecase.FindAllParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockURLRepository_FindAll_Call) Return(uRLs []domain.URL, err error) *MockURLRepository_FindAll_Call {
	_c.Call.Return(uRLs, err)
	return _c
}

func (_c *MockURLRepository_FindAll_Call) RunAndReturn(run func(ctx context.Context, params usecase.FindAllParams) ([]domain.URL, error)) *MockURLRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByOriginalURL provides a mock function for the type MockURLRepository
func (_mock *MockURLRepository) FindByOriginalURL(ctx context.Context, originalURL string) (*domain.URL, error) {
	ret := _mock.Called(ctx, originalURL)

	if len(ret) == 0 {
		panic("no return value specified for FindByOriginalURL")
	}

	var r0 *domain.URL
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.URL, error)); ok {
		return returnFunc(ctx, originalURL)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.URL); ok {
		r0 = returnFunc(ctx, originalURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.URL)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, originalURL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockURLRepository_FindByOriginalURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByOriginalURL'
type MockURLRepository_FindByOriginalURL_Call struct {
	*mock.Call
}

// FindByOriginalURL is a helper method to define mock.On call
//   - ctx context.Context
//   - originalURL string
func (_e *MockURLRepository_Expecter) FindByOriginalURL(ctx interface{}, originalURL interface{}) *MockURLRepository_FindByOriginalURL_Call {
	return &MockURLRepository_FindByOriginalURL_Call{Call: _e.mock.On("FindByOriginalURL", ctx, originalURL)}
}

func (_c *MockURLRepository_FindByOriginalURL_Call) Run(run func(ctx context.Context, originalURL string)) *MockURLRepository_FindByOriginalURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockURLRepository_FindByOriginalURL_Call) Return(uRL *domain.URL, err error) *MockURLRepository_FindByOriginalURL_Call {
	_c.Call.Return(uRL, err)
	return _c
}

func (_c *MockURLRepository_FindByOriginalURL_Call) RunAndReturn(run func(ctx context.Context, originalURL string) (*domain.URL, error)) *MockURLRepository_FindByOriginalURL_Call {
	_c.Call.Return(run)
	return _c
}

// FindByShortCode provides a mock function for the type MockURLRepository
func (_mock *MockURLRepository) FindByShortCode(ctx context.Context, code string) (*domain.URL, error) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for FindByShortCode")
	}

	var r0 *domain.URL
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.URL, error)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.URL); ok {
		r0 = returnFunc(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.URL)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockURLRepository_FindByShortCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByShortCode'
type MockURLRepository_FindByShortCode_Call struct {
	*mock.Call
}

// FindByShortCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockURLRepository_Expecter) FindByShortCode(ctx interface{}, code interface{}) *MockURLRepository_FindByShortCode_Call {
	return &MockURLRepository_FindByShortCode_Call{Call: _e.mock.On("FindByShortCode", ctx, code)}
}

func (_c *MockURLRepository_FindByShortCode_Call) Run(run func(ctx context.Context, code string)) *MockURLRepository_FindByShortCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockURLRepository_FindByShortCode_Call) Return(uRL *domain.URL, err error) *MockURLRepository_FindByShortCode_Call {
	_c.Call.Return(uRL, err)
	return _c
}

func (_c *MockURLRepository_FindByShortCode_Call) RunAndReturn(run func(ctx context.Context, code string) (*domain.URL, error)) *MockURLRepository_FindByShortCode_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockURLRepository
func (_mock *MockURLRepository) Save(ctx context.Context, shortCode string, originalURL string) (*domain.URL, error) {
	ret := _mock.Called(ctx, shortCode, originalURL)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *domain.URL
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*domain.URL, error)); ok {
		return returnFunc(ctx, shortCode, originalURL)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *domain.URL); ok {
		r0 = returnFunc(ctx, shortCode, originalURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.URL)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, shortCode, originalURL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockURLRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockURLRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - shortCode string
//   - originalURL string
func (_e *MockURLRepository_Expecter) Save(ctx interface{}, shortCode interface{}, originalURL interface{}) *MockURLRepository_Save_Call {
	return &MockURLRepository_Save_Call{Call: _e.mock.On("Save", ctx, shortCode, originalURL)}
}

func (_c *MockURLRepository_Save_Call) Run(run func(ctx context.Context, shortCode string, originalURL string)) *MockURLRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockURLRepository_Save_Call) Return(uRL *domain.URL, err error) *MockURLRepository_Save_Call {
	_c.Call.Return(uRL, err)
	return _c
}

func (_c *MockURLRepository_Save_Call) RunAndReturn(run func(ctx context.Context, shortCode string, originalURL string) (*domain.URL, error)) *MockURLRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
