// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	links "go-shortener/services/url-api/internal/handler/links"
	redirect "go-shortener/services/url-api/internal/handler/redirect"
	shorten "go-shortener/services/url-api/internal/handler/shorten"
	"go-shortener/services/url-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// List all links with pagination
				Method:  http.MethodGet,
				Path:    "/links",
				Handler: links.ListLinksHandler(serverCtx),
			},
			{
				// Get link details
				Method:  http.MethodGet,
				Path:    "/links/:code",
				Handler: links.GetLinkDetailHandler(serverCtx),
			},
			{
				// Delete link
				Method:  http.MethodDelete,
				Path:    "/links/:code",
				Handler: links.DeleteLinkHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Redirect to original URL
				Method:  http.MethodGet,
				Path:    "/:code",
				Handler: redirect.RedirectHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Create short URL
				Method:  http.MethodPost,
				Path:    "/urls",
				Handler: shorten.ShortenHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
