// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: analytics.proto

package analyticsclient

import (
	"context"

	"go-shortener/services/analytics-rpc/analytics"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetClickCountRequest  = analytics.GetClickCountRequest
	GetClickCountResponse = analytics.GetClickCountResponse

	Analytics interface {
		GetClickCount(ctx context.Context, in *GetClickCountRequest, opts ...grpc.CallOption) (*GetClickCountResponse, error)
	}

	defaultAnalytics struct {
		cli zrpc.Client
	}
)

func NewAnalytics(cli zrpc.Client) Analytics {
	return &defaultAnalytics{
		cli: cli,
	}
}

func (m *defaultAnalytics) GetClickCount(ctx context.Context, in *GetClickCountRequest, opts ...grpc.CallOption) (*GetClickCountResponse, error) {
	client := analytics.NewAnalyticsClient(m.cli.Conn())
	return client.GetClickCount(ctx, in, opts...)
}
