// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsUnknownError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UNKNOWN_ERROR.String() && e.Code == 500
}

func ErrorUnknownError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UNKNOWN_ERROR.String(), fmt.Sprintf(format, args...))
}

func IsUrlNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_URL_NOT_FOUND.String() && e.Code == 404
}

func ErrorUrlNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_URL_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsUrlExpired(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_URL_EXPIRED.String() && e.Code == 410
}

func ErrorUrlExpired(format string, args ...interface{}) *errors.Error {
	return errors.New(410, ErrorReason_URL_EXPIRED.String(), fmt.Sprintf(format, args...))
}

func IsInvalidUrl(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INVALID_URL.String() && e.Code == 400
}

func ErrorInvalidUrl(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_INVALID_URL.String(), fmt.Sprintf(format, args...))
}

func IsShortCodeExists(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_SHORT_CODE_EXISTS.String() && e.Code == 409
}

func ErrorShortCodeExists(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_SHORT_CODE_EXISTS.String(), fmt.Sprintf(format, args...))
}

func IsInvalidShortCode(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INVALID_SHORT_CODE.String() && e.Code == 400
}

func ErrorInvalidShortCode(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_INVALID_SHORT_CODE.String(), fmt.Sprintf(format, args...))
}
