// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.3
// - protoc             v5.29.2
// source: shortener/v1/shortener.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationShortenerCreateURL = "/shortener.v1.Shortener/CreateURL"
const OperationShortenerDeleteURL = "/shortener.v1.Shortener/DeleteURL"
const OperationShortenerGetURL = "/shortener.v1.Shortener/GetURL"
const OperationShortenerGetURLStats = "/shortener.v1.Shortener/GetURLStats"
const OperationShortenerListURLs = "/shortener.v1.Shortener/ListURLs"
const OperationShortenerRedirectURL = "/shortener.v1.Shortener/RedirectURL"

type ShortenerHTTPServer interface {
	// CreateURL Create a new shortened URL
	CreateURL(context.Context, *CreateURLRequest) (*CreateURLReply, error)
	// DeleteURL Delete a URL
	DeleteURL(context.Context, *DeleteURLRequest) (*DeleteURLReply, error)
	// GetURL Get URL info by short code
	GetURL(context.Context, *GetURLRequest) (*GetURLReply, error)
	// GetURLStats Get URL statistics
	GetURLStats(context.Context, *GetURLStatsRequest) (*GetURLStatsReply, error)
	// ListURLs List all URLs with pagination
	ListURLs(context.Context, *ListURLsRequest) (*ListURLsReply, error)
	// RedirectURL Redirect to original URL (increments click count)
	RedirectURL(context.Context, *RedirectURLRequest) (*RedirectURLReply, error)
}

func RegisterShortenerHTTPServer(s *http.Server, srv ShortenerHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/urls", _Shortener_CreateURL0_HTTP_Handler(srv))
	r.GET("/v1/urls/{short_code}", _Shortener_GetURL0_HTTP_Handler(srv))
	r.GET("/r/{short_code}", _Shortener_RedirectURL0_HTTP_Handler(srv))
	r.GET("/v1/urls/{short_code}/stats", _Shortener_GetURLStats0_HTTP_Handler(srv))
	r.DELETE("/v1/urls/{short_code}", _Shortener_DeleteURL0_HTTP_Handler(srv))
	r.GET("/v1/urls", _Shortener_ListURLs0_HTTP_Handler(srv))
}

func _Shortener_CreateURL0_HTTP_Handler(srv ShortenerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateURLRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShortenerCreateURL)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateURL(ctx, req.(*CreateURLRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateURLReply)
		return ctx.Result(200, reply)
	}
}

func _Shortener_GetURL0_HTTP_Handler(srv ShortenerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetURLRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShortenerGetURL)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetURL(ctx, req.(*GetURLRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetURLReply)
		return ctx.Result(200, reply)
	}
}

func _Shortener_RedirectURL0_HTTP_Handler(srv ShortenerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RedirectURLRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShortenerRedirectURL)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RedirectURL(ctx, req.(*RedirectURLRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RedirectURLReply)
		return ctx.Result(200, reply)
	}
}

func _Shortener_GetURLStats0_HTTP_Handler(srv ShortenerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetURLStatsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShortenerGetURLStats)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetURLStats(ctx, req.(*GetURLStatsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetURLStatsReply)
		return ctx.Result(200, reply)
	}
}

func _Shortener_DeleteURL0_HTTP_Handler(srv ShortenerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteURLRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShortenerDeleteURL)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteURL(ctx, req.(*DeleteURLRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteURLReply)
		return ctx.Result(200, reply)
	}
}

func _Shortener_ListURLs0_HTTP_Handler(srv ShortenerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListURLsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShortenerListURLs)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListURLs(ctx, req.(*ListURLsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListURLsReply)
		return ctx.Result(200, reply)
	}
}

type ShortenerHTTPClient interface {
	CreateURL(ctx context.Context, req *CreateURLRequest, opts ...http.CallOption) (rsp *CreateURLReply, err error)
	DeleteURL(ctx context.Context, req *DeleteURLRequest, opts ...http.CallOption) (rsp *DeleteURLReply, err error)
	GetURL(ctx context.Context, req *GetURLRequest, opts ...http.CallOption) (rsp *GetURLReply, err error)
	GetURLStats(ctx context.Context, req *GetURLStatsRequest, opts ...http.CallOption) (rsp *GetURLStatsReply, err error)
	ListURLs(ctx context.Context, req *ListURLsRequest, opts ...http.CallOption) (rsp *ListURLsReply, err error)
	RedirectURL(ctx context.Context, req *RedirectURLRequest, opts ...http.CallOption) (rsp *RedirectURLReply, err error)
}

type ShortenerHTTPClientImpl struct {
	cc *http.Client
}

func NewShortenerHTTPClient(client *http.Client) ShortenerHTTPClient {
	return &ShortenerHTTPClientImpl{client}
}

func (c *ShortenerHTTPClientImpl) CreateURL(ctx context.Context, in *CreateURLRequest, opts ...http.CallOption) (*CreateURLReply, error) {
	var out CreateURLReply
	pattern := "/v1/urls"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationShortenerCreateURL))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ShortenerHTTPClientImpl) DeleteURL(ctx context.Context, in *DeleteURLRequest, opts ...http.CallOption) (*DeleteURLReply, error) {
	var out DeleteURLReply
	pattern := "/v1/urls/{short_code}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShortenerDeleteURL))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ShortenerHTTPClientImpl) GetURL(ctx context.Context, in *GetURLRequest, opts ...http.CallOption) (*GetURLReply, error) {
	var out GetURLReply
	pattern := "/v1/urls/{short_code}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShortenerGetURL))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ShortenerHTTPClientImpl) GetURLStats(ctx context.Context, in *GetURLStatsRequest, opts ...http.CallOption) (*GetURLStatsReply, error) {
	var out GetURLStatsReply
	pattern := "/v1/urls/{short_code}/stats"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShortenerGetURLStats))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ShortenerHTTPClientImpl) ListURLs(ctx context.Context, in *ListURLsRequest, opts ...http.CallOption) (*ListURLsReply, error) {
	var out ListURLsReply
	pattern := "/v1/urls"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShortenerListURLs))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ShortenerHTTPClientImpl) RedirectURL(ctx context.Context, in *RedirectURLRequest, opts ...http.CallOption) (*RedirectURLReply, error) {
	var out RedirectURLReply
	pattern := "/r/{short_code}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShortenerRedirectURL))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
